gulpjs/plugins

- src/blackList.json
Duplicate of [gulp-6to5](https://www.npmjs.com/package/gulp-6to5/).
> Blacklist gulp-es6to5

- src/blackList.json
As suggested by @phated in https://github.com/gulpjs/plugins/pull/158#issuecomment-74567144.
> Add `gulp-6to5` to the blacklist

- src/blackList.json
This plugin is in many ways against our guidelines:
* It doesn't provide real documentation.
* It doesn't have any tests. (well technically it has, but https://github.com/daxingplay/gulp-css-combo/blob/master/test.js)
* It basically does nothing :) It's still an exact copy of `gulp-plugin-boilerplate`, tho it's published to npm.
> Blacklist `gulp-css-combo`

- src/blackList.json
The `gulp-ember-handlebars` plugin was blocked because it's `duplicate of gulp-handlebars & too complex`, so this one needs to be blacklisted too. `gulp-ember-handlebarz` is a fork of `gulp-ember-handlebars` but nothing actually changed.
> Blacklist `gulp-ember-handlebarz`

- src/blackList.json
> Blacklist `gulp-git-pages`

- src/blackList.json
People can perfectly use the `buildbranch` module directly. The module even provides documentation on how to use it directly: https://github.com/nfroidure/buildbranch#build-system.
> Blacklist gulp-build-branch

- src/blackList.json
duplicate of gulp-concat-json, missing documentation
> blacklist `gulp-concat-json2`

- src/blackList.json
no documentation, duplicate of gulp-streamlinejs
> Blacklist `gulp-streamline`

- src/blackList.json
`gulp-origin-stylus` https://www.npmjs.com/package/gulp-origin-stylus is a duplicate of `gulp-stylus`
> Add gulp-origin-stylus to the blacklist

- src/blackList.json
> Add `gulp-retina-sprite` to blackList

- src/blackList.json
This plugin's source code [is totally empty](https://github.com/pasangsherpa/gulp-handlebars-compiler/blob/master/index.js), although it's published to npm. I will create an issue in its repo.
> Blacklist `gulp-handlebars-compiler`

- Gulpfile.js
Introduced in https://github.com/gulpjs/plugins/commit/10898426ed641c4c903278c9067aaf3680e8f356.
> Gulpfile: fix syntax error

- src/blackList.json
gulp-add-src has very different functionality and objectives from gulp-inject (please see respective README.md files)
> Removed gulp-add-src from the blacklist 

- src/blackList.json
Calling gulp from node is [already a hack](http://macr.ae/article/gulp-casperjs.html), this plugin just seems to be wrapping it in a gulp plugin.
https://github.com/NullRefExcep/gulp-casperjs/blob/master/index.js#L40-L47
I'm pretty sure this shouldn't be a gulp plugin.
Also, isn't it duplicating every file? [here](https://github.com/NullRefExcep/gulp-casperjs/blob/master/index.js#L32-L34)
> Added gulp-casperjs to blacklist

- src/blackList.json
I saw there were a lot typescript plugins on the registry, a big part of them are duplicates of `gulp-typescript`:
- `gulp-tsb` provides the same functionality as `gulp-typescript`
- `gulp-tsc-sushicutta` is a clone of `gulp-tsc` which is a duplicate of `gulp-typescript`
- `gulp-type` has been renamed to `gulp-typescript`
- `gulp-typescript-alpha-1.5.0` is a clone of `gulp-typescript`, only with a default of a setting changed
- `gulp-typescript-package` is a plugin that compiles and uglifies typescript files, which can easily be done using `gulp-typescript`, `gulp-uglify` & `gulp.dest`.
> Add various typescript plugins to blacklist

- src/blackList.json
This plugin does not uses the stream API.
> Blacklist gulp-electron

- src/blackList.json
As it's a dupe of https://www.npmjs.com/package/gulp-babel/.  I have no idea how to notify
the creator as the plugin is not open source it seems.
> Blacklist `gulp-babel-transpiler`

- src/blackList.json
Flagrant duplicate of an existing plugin.
- The real thing: https://github.com/crissdev/gulp-props
- Duplicate: https://github.com/ValeryIvanov/gulp-props2json
You may also consider to blacklist [gulp-properties](https://www.npmjs.com/package/gulp-properties) which is an empty package for quite a while.
Thanks.
> Blacklist gulp-props2json

- package.json
- src/css/style.css
Updated `gulp-autoprefixer` to latest version because of deprecation warning. 
Added line spacing to tags. 
Changed tag color to match the logo color which is slightly lighter than it was. 
Changes were made as per this issue https://github.com/gulpjs/plugins/issues/119
> Bumped gulp-autoprefixer. Added line spacing between tags and lightened font color.

- src/index.html
Use updated npm URL to avoid unnecessary redirects.
> Avoid unnecessary redirects.

- src/blackList.json
The package now also contains a deprecation message that suggests the use of gulp-refresh.
> Add gulp.livereload to blacklist

- src/blackList.json
With the release of [gulp-rollup](https://github.com/mcasimir/gulp-rollup) v2, this plugin no longer breaks the guidelines as far as I know. It will only read from the filesystem if the user explicitly allows it through an option.
> Unblacklist gulp-rollup

- src/blackList.json
[This plugin reads from the filesystem directly, which is what the original gulp-rollup was blacklisted for.](https://github.com/MikeKovarik/gulp-better-rollup/issues/2) gulp-rollup still doesn't show up in the plugin search (has the blacklist not been updated?), but gulp-better-rollup does, and I'm not having it.
> Blacklist gulp-better-rollup
